/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraigrafico;

/**
 *
 * @author Usuario
 */
public class CalculadoraGrafica extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGrafica
     */
    public CalculadoraGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IpField = new javax.swing.JTextField();
        MaskField = new javax.swing.JTextField();
        CalcularButton = new javax.swing.JButton();
        AddressIpLabel = new javax.swing.JLabel();
        NetMaskLabel = new javax.swing.JLabel();
        SlashLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        NetmaskLabel = new javax.swing.JLabel();
        NetworkLabel = new javax.swing.JLabel();
        HostMinLabel = new javax.swing.JLabel();
        HostMaxLabel = new javax.swing.JLabel();
        BroadcastLabel = new javax.swing.JLabel();
        HostsNetLabel = new javax.swing.JLabel();
        AddressLabelDecimal = new javax.swing.JLabel();
        AddressLabelBinary = new javax.swing.JLabel();
        NetMaskLabelDecimal = new javax.swing.JLabel();
        NetmaskLabelBinary = new javax.swing.JLabel();
        NetworkLabelDecimal = new javax.swing.JLabel();
        NetworkLabelBinary = new javax.swing.JLabel();
        HostMinLabelDecimal = new javax.swing.JLabel();
        HostMinLabelBinary = new javax.swing.JLabel();
        HostMaxLabelDecimal = new javax.swing.JLabel();
        HostMaxLabelBinary = new javax.swing.JLabel();
        BroadcastLabelDecimal = new javax.swing.JLabel();
        BroadcastLabelBinary = new javax.swing.JLabel();
        HostNetCountLabel = new javax.swing.JLabel();
        HostNetTypeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IpField.setText("192.16.0.1");
        IpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpFieldActionPerformed(evt);
            }
        });

        MaskField.setText("24");

        CalcularButton.setText("Calcular");
        CalcularButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcularButtonMouseClicked(evt);
            }
        });

        AddressIpLabel.setText("Address Ip");

        NetMaskLabel.setText("Netmask");

        SlashLabel.setText("/");

        AddressLabel.setText("Address:");

        NetmaskLabel.setText("Netmask:");

        NetworkLabel.setText("Network:");

        HostMinLabel.setText("HostMin:");

        HostMaxLabel.setText("HostMax:");

        BroadcastLabel.setText("Broadcast:");

        HostsNetLabel.setText("Hosts/Net:");

        AddressLabelDecimal.setText(" ");

        AddressLabelBinary.setText(" ");

        NetMaskLabelDecimal.setText(" ");

        NetmaskLabelBinary.setText(" ");

        NetworkLabelDecimal.setText(" ");

        NetworkLabelBinary.setText(" ");

        HostMinLabelDecimal.setText(" ");

        HostMinLabelBinary.setText(" ");

        HostMaxLabelDecimal.setText(" ");

        HostMaxLabelBinary.setText(" ");

        BroadcastLabelDecimal.setText(" ");

        BroadcastLabelBinary.setText(" ");

        HostNetCountLabel.setText(" ");

        HostNetTypeLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HostsNetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HostNetCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HostNetTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AddressIpLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IpField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(SlashLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddressLabelDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CalcularButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HostMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HostMaxLabelDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HostMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HostMinLabelDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NetworkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NetworkLabelDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NetmaskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NetMaskLabelDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NetmaskLabelBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddressLabelBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MaskField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(NetMaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HostMinLabelBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NetworkLabelBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HostMaxLabelBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BroadcastLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BroadcastLabelDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BroadcastLabelBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressIpLabel)
                    .addComponent(NetMaskLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaskField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlashLabel))
                .addGap(18, 18, 18)
                .addComponent(CalcularButton)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressLabelDecimal)
                    .addComponent(AddressLabelBinary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetmaskLabel)
                    .addComponent(NetMaskLabelDecimal)
                    .addComponent(NetmaskLabelBinary))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetworkLabel)
                    .addComponent(NetworkLabelDecimal)
                    .addComponent(NetworkLabelBinary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostMinLabel)
                    .addComponent(HostMinLabelDecimal)
                    .addComponent(HostMinLabelBinary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostMaxLabel)
                    .addComponent(HostMaxLabelDecimal)
                    .addComponent(HostMaxLabelBinary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BroadcastLabel)
                    .addComponent(BroadcastLabelDecimal)
                    .addComponent(BroadcastLabelBinary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostsNetLabel)
                    .addComponent(HostNetCountLabel)
                    .addComponent(HostNetTypeLabel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpFieldActionPerformed

    private void CalcularButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularButtonMouseClicked
        String ipAddress = IpField.getText()+"/"+MaskField.getText();
        IPv4Address dir = new IPv4Address(ipAddress.split("/")[0], ipAddress.split("/")[1]);
        AddressLabelDecimal.setText(dir.getIPAddress());
        AddressLabelBinary.setText(dir.getBinaryAddress());
        NetMaskLabelDecimal.setText(dir.getDecimalMask()+" = "+ipAddress.split("/")[1]);
        NetmaskLabelBinary.setText(dir.getBinaryMask());
        NetworkLabelDecimal.setText(dir.getDecimalNetwork()+dir.getCIDRMask());
        NetworkLabelBinary.setText(dir.getBinaryNetwork());
        HostMinLabelDecimal.setText(dir.getDecimalFirstHost());
        HostMinLabelBinary.setText(dir.getBinaryFirstHost());
        HostMaxLabelDecimal.setText(dir.getDecimalLastHost());
        HostMaxLabelBinary.setText(dir.getBinaryLastHost());
        BroadcastLabelDecimal.setText(dir.getDecimalBroadcast());
        BroadcastLabelBinary.setText(dir.getBinaryBroadcast());
        HostNetCountLabel.setText(String.format("%.0f", dir.getMaxHosts()));
        HostNetTypeLabel.setText("Tipo de red: "+dir.getType());
    }//GEN-LAST:event_CalcularButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressIpLabel;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel AddressLabelBinary;
    private javax.swing.JLabel AddressLabelDecimal;
    private javax.swing.JLabel BroadcastLabel;
    private javax.swing.JLabel BroadcastLabelBinary;
    private javax.swing.JLabel BroadcastLabelDecimal;
    private javax.swing.JButton CalcularButton;
    private javax.swing.JLabel HostMaxLabel;
    private javax.swing.JLabel HostMaxLabelBinary;
    private javax.swing.JLabel HostMaxLabelDecimal;
    private javax.swing.JLabel HostMinLabel;
    private javax.swing.JLabel HostMinLabelBinary;
    private javax.swing.JLabel HostMinLabelDecimal;
    private javax.swing.JLabel HostNetCountLabel;
    private javax.swing.JLabel HostNetTypeLabel;
    private javax.swing.JLabel HostsNetLabel;
    private javax.swing.JTextField IpField;
    private javax.swing.JTextField MaskField;
    private javax.swing.JLabel NetMaskLabel;
    private javax.swing.JLabel NetMaskLabelDecimal;
    private javax.swing.JLabel NetmaskLabel;
    private javax.swing.JLabel NetmaskLabelBinary;
    private javax.swing.JLabel NetworkLabel;
    private javax.swing.JLabel NetworkLabelBinary;
    private javax.swing.JLabel NetworkLabelDecimal;
    private javax.swing.JLabel SlashLabel;
    // End of variables declaration//GEN-END:variables
}
